### ISSUE TITLE
Turborepo’s schema replaced 'pipeline' field with 'tasks' field.

### ISSUE THREAD

**Issue by Conceivian** [chatbotkit/node-sdk#2]
I am seeing lint errors

[{
	"resource": "/Users/avib/AviDev/experiments/chatbotkit-node-sdk/turbo.json",
	"owner": "_generated_diagnostic_collection_name_#3",
	"severity": 4,
	"message": "Missing property \"tasks\".",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
},{
	"resource": "/Users/avib/AviDev/experiments/chatbotkit-node-sdk/turbo.json",
	"owner": "_generated_diagnostic_collection_name_#3",
	"severity": 4,
	"message": "Property pipeline is not allowed.",
	"startLineNumber": 3,
	"startColumn": 3,
	"endLineNumber": 3,
	"endColumn": 13
}]

**Comment by pdparchitect** [comment]
Thanks. This issue will be fixed in the next release.

**Comment by pdparchitect** [comment]
This is now fixed. Thanks.
