### ISSUE TITLE
Instructions needs updating 

### ISSUE THREAD

**Issue by Gleeful2862** [chatbotkit/node-sdk#3]
Looks like the repo has been updated to require using `pnpm` instead of  `npm` - but the instructions are still suggesting to use `npm`.

```
npm install @chatbotkit/sdk
```

Also - when I run `pnpm install @chatbotkit/sdk` - I am getting 

```
ERR_PNPM_ADDING_TO_ROOT  Running this command will add the dependency to the workspace root, which might not be what you want - if you really meant it, make it explicit by running this command again with the -w flag (or --workspace-root). If you don't want to see this warning anymore, you may set the ignore-workspace-root-check setting to true.
```
**Does the dependency need to be really added to workspace root?**

**Comment by pdparchitect** [comment]
We need to make this clear. These instructions are for how to install the sdk... not for the development usage. I will make sure this is captured upon the next release.

**Comment by pdparchitect** [comment]
This has now been fixed! Thanks.
